### ISSUE TITLE
Update for Plasma6

### ISSUE THREAD

**Issue by alexankitty** [alexankitty/FancyTasks#34]
Update the code base once Plasma6 is out, or more or less finalized.

**Comment by alexankitty** [comment]
When the update for plasma6 comes out, the existing 5 compatible version will be moved to its own branch.

**Comment by alexankitty** [comment]
Release date is expected to be February 2024. Once I have a release candidate to work from I'll start updating the existing code base for it.

**Comment by alexankitty** [comment]
KF6 Porting
https://develop.kde.org/docs/plasma/widget/porting_kf6/

**Comment by theS1LV3R** [comment]
Any updates? Plasma 6 is now out, and is starting to hit distros as well (e.g. Arch earlier today)

**Comment by alexankitty** [comment]
Hold off on updating if you want to use it.
I'm a little burnt out on programming at the moment since I do a ton of it for my day job as well and still need to finish the indicator and color rewrites that way 5 doesn't get left behind for the LTS people. 
It'll be a bit before this is done as I've not even started.

**Comment by alexankitty** [comment]
Figured I'd provide an update on where we're at towards preparations for plasma6.
The button overhaul is completed and working, you can checkout the Color-Overhaul branch and install it should you want to see where it's at. Things can and will break at any given time.
I'm probably somewhere between 30-50% done with everything else that needs to be completed.
Currently working on the indicator overhaul which should alleviate a ton of the existing issues with them, and also make the codebase a lot more maintainable.
Once that's done, the preset system needs to be built, and then that should be everything that's needed to move it into a plasma5 fork of the repository. From there, only major breaking changes will be worked on.

For the porting, since this is based on the upstream task manager Eike made, in addition to actually porting the plasmoid to run on 6, any features that have seen been added to the task manager will also need to be backported and integrated with some of the fixes and feature adds FancyTasks does.

I don't have an exact timeline for completion here, but I'm hoping by the end of the week we can look towards porting.

Sorry about how long this has taken to get done, I got stuck in a code maintainability nightmare that I finally got figured out over the weekend.

**Comment by alexankitty** [comment]
Sneak peak of the new indicator screen
![image](https://github.com/alexankitty/FancyTasks/assets/45508320/2f384867-184c-429e-9d8b-36667f3ef58f)

**Comment by IF-Adin** [comment]
Thank you so much for all your hard work porting this to Plasma6 ❤️

**Comment by GordonZed** [comment]
> Sneak peak of the new indicator screen ![image](https://private-user-images.githubusercontent.com/45508320/317951732-2f384867-184c-429e-9d8b-36667f3ef58f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3MTE0OTQsIm5iZiI6MTcxNzcxMTE5NCwicGF0aCI6Ii80NTUwODMyMC8zMTc5NTE3MzItMmYzODQ4NjctMTg0Yy00MjllLTlkOGItMzY2NjdmM2VmNThmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDIxNTk1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5Y2U2YmYzZjA2ZTc5Y2NiMjIzZTNlNDFjNzRhY2JjNDNkNzIwYWM3OThmMTg3YzQzYjYwMDVhYjFiYTA1NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hn4RLNTaJnn-u4djA5-qPFPfH3ydzcPFwYuPWqO-dyw)

You're a gangster. Really appreciate this widget making the task manager usable, but having experienced burnout myself in the last year: please for the love of God, take all the time you need.

Thanks for keeping this project up and running though. Will patiently await updates. Would love to contribute myself one day when I have the time and energy.

**Comment by luisbocanegra** [comment]
So I tried to port main branch to plasma 6 by merging with upstream...

And after 20+ merge conflicts it's working! Well... kinda working, there are some things broken and others I haven't tested.

![Screenshot_20241110_213024](https://github.com/user-attachments/assets/c9050bbd-9d50-43f1-a3e3-608f7317f123)

I pushed the code [here](https://github.com/luisbocanegra/FancyTasks/tree/plasma6) if someone wants to try it out.

Will try to take a look at Color-Overhaul branch and see if I can help with that in the upcoming weeks.

**Comment by alexankitty** [comment]
I'm still not ready to port this until I finish the 5.0 rewrite and changes.
Been struggling with burnout though so it might be a bit. It's good to know
though that getting it functional won't be too much of a hassle.

**Comment by rqn17** [comment]
I DO LOVE FancyTasks.
Thanks to @alexankitty for this great widget!
But since I upgraded KDE to plasma6, I can't use it anymore... 
Congratulations to @luisbocanegra for trying to port to Plasma6. I wanted to test this version. I downloaded the package and ran ./install.sh. 
I ran into this issue : 
kf.package: Invalid metadata for package structure “Plasma/Applet” Package type “Plasma/Applet” not found
I can't place the widget in a panel: I get a message explaining that “This widget was written for an unknow older version...”.
I'm not a developer (unfortunately). Can you explain to me how to install?

**Comment by IF-Adin** [comment]
@rqn17 

`{
    "KPlugin": {
        "Authors": [
            {
                "Email": "Hein@kde.org, ideas@alexankitty.com",
                "Name": "Eike Hein, Alexandra Stone",
                "Name[ar]": "Eike Hein, Alexandra Stone",
                "Name[az]": "Eike Hein, Alexandra Stone",
                "Name[bg]": "Eike Hein, Alexandra Stone",
                "Name[ca@valencia]": "Eike Hein, Alexandra Stone",
                "Name[ca]": "Eike Hein, Alexandra Stone",
                "Name[cs]": "Eike Hein, Alexandra Stone",
                "Name[da]": "Eike Hein, Alexandra Stone",
                "Name[de]": "Eike Hein, Alexandra Stone",
                "Name[en_GB]": "Eike Hein, Alexandra Stone",
                "Name[es]": "Eike Hein, Alexandra Stone",
                "Name[eu]": "Eike Hein, Alexandra Stone",
                "Name[fi]": "Eike Hein, Alexandra Stone",
                "Name[fr]": "Eike Hein, Alexandra Stone",
                "Name[hu]": "Eike Hein, Alexandra Stone",
                "Name[ia]": "Eike Hein, Alexandra Stone",
                "Name[id]": "Eike Hein, Alexandra Stone",
                "Name[it]": "Eike Hein, Alexandra Stone",
                "Name[ja]": "Eike Hein, Alexandra Stone",
                "Name[ka]": "აიკე ჰაინი",
                "Name[ko]": "Eike Hein, Alexandra Stone",
                "Name[lt]": "Eike Hein, Alexandra Stone",
                "Name[nl]": "Eike Hein, Alexandra Stone",
                "Name[nn]": "Eike Hein, Alexandra Stone",
                "Name[pa]": "ਇਕੀ ਹੀਇਨ",
                "Name[pl]": "Eike Hein, Alexandra Stone",
                "Name[pt]": "Eike Hein, Alexandra Stone",
                "Name[pt_BR]": "Eike Hein, Alexandra Stone",
                "Name[ro]": "Eike Hein, Alexandra Stone",
                "Name[ru]": "Eike Hein, Alexandra Stone",
                "Name[sk]": "Eike Hein, Alexandra Stone",
                "Name[sl]": "Eike Hein, Alexandra Stone",
                "Name[sv]": "Eike Hein, Alexandra Stone",
                "Name[ta]": "எய்கே ஹைன்",
                "Name[tr]": "Eike Hein, Alexandra Stone",
                "Name[uk]": "Eike Hein, Alexandra Stone",
                "Name[vi]": "Eike Hein, Alexandra Stone",
                "Name[x-test]": "xxEike Hein, Alexandra Stonexx",
                "Name[zh_CN]": "Eike Hein, Alexandra Stone"
            }
        ],
        "Category": "Windows and Tasks",
        "Description": "More modern taskbar-style window switcher displaying icons and text, with some improvments and customization options.",
        "Description[ar]": "مبدل نوافذ تقليدي بنمط شريط المهام يعرض الأيقونات والنص",
        "Description[az]": "Nişanlar və mətn göstərən klassik tapşırıq paneli üslubunda pəncərə dəyişdirici",
        "Description[bg]": "Класически превключвател на прозорци в стил лента на задачите, показващ икони и текст",
        "Description[ca@valencia]": "Commutador de finestres clàssic d'estil barra de tasques que mostra les icones i text",
        "Description[ca]": "Commutador de finestres clàssic d'estil barra de tasques que mostra les icones i text",
        "Description[da]": "Klassisk opgavelinje-agtig vinduesskifter som viser ikoner og tekst",
        "Description[en_GB]": "Classic taskbar-style window switcher displaying icons and text",
        "Description[es]": "Selector de ventanas al estilo de la barra de tareas clásica que muestra iconos y texto",
        "Description[eu]": "Ataza-barra tankerako leiho aldatzaile klasikoa ikonoak eta testua azaltzen dituena",
        "Description[fi]": "Perinteinen tehtäväpalkkimainen ikkunavaihto kuvakkein ja tekstein",
        "Description[fr]": "Sélecteur classique de fenêtres en barre des tâches, affichant des icônes et du texte",
        "Description[ia]": "Moderne Commutator de fenestra de stilo a barra de carga monstrante  icones e texto",
        "Description[id]": "Pengalih window gaya taskbar klasik yang menampilkan ikon dan teks",
        "Description[it]": "Scambiatore di finestre classico in stile barra delle applicazioni che mostra icone e testo",
        "Description[ja]": "アイコンとテキストを表示するタスクバースタイルのウィンドウスイッチャー",
        "Description[ka]": "ფანჯრების კლასიკური გადამრთველი, ხატულებსა და ტექსტის ჩვენებით",
        "Description[ko]": "아이콘과 텍스트를 표시하는 고전 작업 표시줄 스타일 창 전환기",
        "Description[nl]": "Klassieke taakbalkstijl vensterschakelaar met tonen van pictogrammen en tekst",
        "Description[nn]": "Klassisk vindaugsbytar med oppgåvelinje med ikon og tekst",
        "Description[pl]": "Klasyczny przełącznik okien, wyświetlający ikony i tekst na pasku zadań",
        "Description[pt]": "Selector de janelas clássico em tarefas que mostra ícones e texto",
        "Description[pt_BR]": "Seletor de janelas estilo barra de tarefas clássico mostrando ícones e texto",
        "Description[ro]": "Comutator de ferestre clasic cu bară de sarcini, afișând pictograme și text",
        "Description[ru]": "Классический вариант панели задач, использующий значки и текст",
        "Description[sk]": "Klasický prepínač okien v štýle panela úloh zobrazujúci ikony a text",
        "Description[sl]": "Klasični preklopnik oken z vrstico opravil, ki prikazuje ikone in besedilo",
        "Description[sv]": "Klassiskt fönsterbytare med aktivitetsliknande fönster som visar ikoner och text",
        "Description[ta]": "சின்னங்களையும் பெயர்களையும் காட்டும் சாளர மாற்றி",
        "Description[tr]": "Klasik görev çubuğu tarzı, simgeler ve metin görüntüleyen pencere değiştiricisi",
        "Description[uk]": "Класичний перемикач вікон у стилі панелі задач з показом піктограм і тексту",
        "Description[vi]": "Trình chuyển cửa sổ phong cách thanh tác vụ cổ điển, hiển thị biểu tượng và chữ",
        "Description[x-test]": "xxClassic taskbar-style window switcher displaying icons and textxx",
        "Description[zh_CN]": "经典风格的同时显示图标和文本的任务栏式窗口切换器",
        "EnabledByDefault": true,
        "Icon": "FancyTasks.png",
        
        "Id": "alexankitty.fancytasks",
        "License": "GPL-2.0+",
        "Name": "Fancy Tasks",
        "Name[af]": "Taakbestuurder",
        "Name[ar]": "مدير المهام",
        "Name[ast]": "Xestor de xeres",
        "Name[az]": "Tapşırıq Meneceri",
        "Name[be@latin]": "Kiraŭnik zadańniaŭ",
        "Name[be]": "Кіраванне заданнямі",
        "Name[bg]": "Управление на задачи",
        "Name[bn]": "টাস্ক ম্যানেজার",
        "Name[bs]": "Menadžer zadataka",
        "Name[ca@valencia]": "Gestor de tasques",
        "Name[ca]": "Gestor de tasques",
        "Name[cs]": "Správce úloh",
        "Name[csb]": "Menedżer dzejaniów",
        "Name[da]": "Opgavelinje",
        "Name[de]": "Fensterleiste",
        "Name[el]": "Διαχειριστής εργασιών",
        "Name[en_GB]": "Fancy Tasks",
        "Name[eo]": "Taskadministrilo",
        "Name[es]": "Gestor de tareas",
        "Name[et]": "Tegumihaldur",
        "Name[eu]": "Ataza-kudeatzailea",
        "Name[fi]": "Tehtävienhallinta",
        "Name[fr]": "Gestionnaire de tâches",
        "Name[fy]": "Taakbehearder",
        "Name[ga]": "Bainisteoir na dTascanna",
        "Name[gl]": "Xestor de tarefas",
        "Name[gu]": "ટાસ્ક વ્યવસ્થાપક",
        "Name[he]": "מנהל משימות",
        "Name[hi]": "कार्य प्रबंधक",
        "Name[hne]": "काम प्रबंधक",
        "Name[hr]": "Upravljanje zadacima",
        "Name[hsb]": "Rjadowar nadawkow",
        "Name[hu]": "Feladatkezelő",
        "Name[ia]": "Gerente de carga",
        "Name[id]": "Fancy Tasks",
        "Name[is]": "Verkefnastjóri",
        "Name[it]": "Gestore dei processi",
        "Name[ja]": "タスクマネージャ",
        "Name[ka]": "ამოცანების მმართველი",
        "Name[kk]": "Тапсырмалар менеджері",
        "Name[km]": "កម្មវិធី​គ្រប់គ្រង​ភារកិច្ច",
        "Name[kn]": "ಕಾರ್ಯ ವ್ಯವಸ್ಥಾಪಕ (ಟಾಸ್ಕ್ ಮ್ಯಾನೇಜರ್)",
        "Name[ko]": "작업 관리자",
        "Name[lt]": "Užduočių tvarkytuvė",
        "Name[lv]": "Uzdevumu pārvaldnieks",
        "Name[mk]": "Менаџер на апликации",
        "Name[ml]": "ടാസ്ക് മാനേജര്‍",
        "Name[mr]": "कार्य व्यवस्थापक",
        "Name[nb]": "Oppgavebehandler",
        "Name[nds]": "Opgavenpleger",
        "Name[ne]": "कार्य प्रबन्धक",
        "Name[nl]": "Takenbeheer",
        "Name[nn]": "Oppgåve­handsamar",
        "Name[or]": "କାର୍ଯ୍ୟ ପରିଚାଳକ",
        "Name[pa]": "ਟਾਸਕ ਮੈਨੇਜਰ",
        "Name[pl]": "Paskowy przełącznik zadań",
        "Name[pt]": "Gestor de Tarefas",
        "Name[pt_BR]": "Gerenciador de tarefas",
        "Name[ro]": "Gestionar de sarcini",
        "Name[ru]": "Панель задач",
        "Name[se]": "Bargogieđahalli",
        "Name[si]": "කාර්‍යය කළමණාකරු",
        "Name[sk]": "Správca úloh",
        "Name[sl]": "Upravljalnik opravil",
        "Name[sr@ijekavian]": "менаџер задатака",
        "Name[sr@ijekavianlatin]": "menadžer zadataka",
        "Name[sr@latin]": "menadžer zadataka",
        "Name[sr]": "менаџер задатака",
        "Name[sv]": "Aktivitetshanterare",
        "Name[ta]": "பணி மேலாளர்",
        "Name[te]": "కర్తవ్య నిర్వాహకి",
        "Name[tg]": "Мудири вазифаҳо",
        "Name[th]": "จัดการงาน",
        "Name[tr]": "Görev Yöneticisi",
        "Name[ug]": "ۋەزىپە باشقۇرغۇچ",
        "Name[uk]": "Менеджер задач",
        "Name[uz@cyrillic]": "Вазифа бошқарувчиси",
        "Name[uz]": "Vazifa boshqaruvchisi",
        "Name[vi]": "Trình quản lí tác vụ",
        "Name[wa]": "Manaedjeu des bouyes",
        "Name[x-test]": "xxFancy Tasksxx",
        "Name[zh_CN]": "任务管理器",
        "Name[zh_TW]": "含描述文字的工作管理員",
        "Version": "4.0",
        "Website": "https://github.com/alexankitty/FancyTasks"
    },
    "X-Plasma-API-Minimum-Version": "6.0",
    "KPackageStructure": "Plasma/Applet",
    "X-Plasma-API": "declarativeappletscript",
    "X-Plasma-MainScript": "ui/main.qml",
    "X-Plasma-Provides": [
        "org.kde.plasma.multitasking"
    ]
}
`
I changed the metadata.json as such and not it allws me to add the plasmoid, but now it throws the error:
/.local/share/plasma/plasmoids/alexankitty.fancytasks/contents/ui/main.qml:379:5: TaskManagerApplet.DragHelper is not a type

**Comment by IF-Adin** [comment]
@luisbocanegra Thank you for the help. Unfortunately, this error message remains:

alexankitty.fancytasks/contents/ui/main.qml:379:5: TaskManagerApplet.DragHelper is not a type

**Comment by luisbocanegra** [comment]
@IF-Adin you're still using the plasma 5 main (the main branch) that line in your error does not exist in the plasma6 code

**Comment by rqn17** [comment]
@luisbocanegra: great, it works!
The size of the icons is a little small compared to the height of the panel. How can we fix it ?

**Comment by alexankitty** [comment]
I'm not going to make any guarantees about this getting done. At the moment I use hyprland which has no support for plasmoids. At some point I want to create my own panel that would be plasmoid compatible which would give me incentive to work on things like this, but for the foreseeable future I don't know when or if I'll get to this. The project is open source, if anyone wants to PR to fix it they can and I'll get it merged, or they can maintain their own fork of it.
